---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  annotations:
    force-update: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: hamedfakoori1991/{{ .Values.appName }}:v3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: ASPNETCORE_URLS
          value: http://*:5000
        - name: ASPNETCORE_ENVIRONMENT
          value: Kubernetes
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: secret-appsettings
              key: connection-string
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
  selector:
    app: {{ .Values.appName }}
