apiVersion: v1
kind: Secret
metadata:
  name: secret-appsettings
type: Opaque
data:
  connection-string: U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPVBpenphO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9eW91clN0cm9uZyghKVBhc3N3b3JkO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZQ==